default_platform(:android)

platform :android do

before_all do
    ENV["APPSWEEP_API_KEY"]="gs_appsweep_BQc20zl_ptXq7Tv5enXus4lR6FsPEQN4PFW0MsvR"
  end
#     Upload All
    lane :releaseapp do
        clean()
            begin
                buildapk()
            rescue => exception
                #slackdexguarderror(exception)
            end
        #copyapk()
        uploadtofirebaseappdistribution()
        uploadtoAppSweap()
        #appknoxaccesstoken()
        #uploadtofirebasetestlab()
    end

    lane :uploadtoAppSweap do
        #sh("export APPSWEEP_API_KEY=gs_appsweep_BQc20zl_ptXq7Tv5enXus4lR6FsPEQN4PFW0MsvR")
        sh("guardsquare scan /Users/rmltech/AndroidStudioProjects/rml-demo-apps/app/build/outputs/apk/release/app-release-protected.apk")
    end

#     Upload Without Appknox
    lane :releaseappwithoutuploadappknox do
        clean()
        begin
            buildapk()
        rescue => exception
            #slackdexguarderror(exception)
        end
        uploadtofirebaseappdistribution()
        uploadtofirebasetestlab()
    end

#     Upload Without Firebase
    lane :releaseappwithoutuploadfirebase do
        clean()
         begin
            buildapk()
         rescue => exception
             #slackdexguarderror(exception)
         end
          copyapk()
          appknoxaccesstoken()
    end

#     Jenkins
    lane :jenkins do
        clean()
         begin
            buildapk()
         rescue => exception
            #slackdexguarderror(exception)
         end
         copyapk()
    end

#     Clean Project
    lane :clean do
        gradle(
          task: "clean",
          project_dir: "/Users/rmltech/AndroidStudioProjects/rml-demo-apps"
        )
    end

#     Build Application Release
    lane :buildapk do
        gradle(
          task: 'assemble',
          build_type: 'Release',
        )
        #slackdexguardsuccess
    end



#     Copy Protected App for Upload to Appknox
    lane :copyapk do
        APK_LOCATION = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
        sh("cp #{APK_LOCATION} /Users/rmltech/Documents/Appknox/Fastlane-App")
    end

#     Firebase App Distribution Get Latest Version Code
    lane :increment_version do
        latest_release = firebase_app_distribution_get_latest_release(
          app: "1:954269003292:android:b4099e7352481e8e6239d9",
          firebase_cli_token: "1//0gt-XjFucD2qDCgYIARAAGBASNwF-L9IrXg1q10HqDfGeWS5J2f7NzFyYWHwvmBuy46cS1xFiClbPJ_pDzCYoKjxiXEZs6kytMDI"
        )
        increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
    end

#     Upload Application Protected to Firebase Distribution App
    lane :uploadtofirebaseappdistribution do
        increment_version()
        release = firebase_app_distribution(
              app: "1:954269003292:android:b4099e7352481e8e6239d9",
              firebase_cli_token: "1//0gt-XjFucD2qDCgYIARAAGBASNwF-L9IrXg1q10HqDfGeWS5J2f7NzFyYWHwvmBuy46cS1xFiClbPJ_pDzCYoKjxiXEZs6kytMDI",
              testers: "nikkirufiansya2@gmail.com, technicalrml2023@gmail.com",
               release_notes: "dexguard 9.4.23 enable root for testing"
        )
        #slackfirebasedistributionappsuccess()
    end


#     Export Access Token Appknox
    lane :appknoxaccesstoken do
        sh("export APPKNOX_ACCESS_TOKEN=156e23bde8e3506cc5fd1bc8ae49b9d2a2d689ab")
        appknoxwhoami()
        uploadtoappknox()
    end

#     Get Credential Appknox
    lane :appknoxwhoami do
        sh("/usr/local/bin/appknox whoami --access-token 156e23bde8e3506cc5fd1bc8ae49b9d2a2d689ab")
    end

#     Upload Protected App to Appknox
    lane :uploadtoappknox do
        begin
            sh("/usr/local/bin/appknox upload /Users/rmltech/Documents/Appknox/Fastlane-App/app-release-protected.apk | xargs /usr/local/bin/appknox cicheck --risk-threshold critical")
            #slackappknoxsuccess()
        rescue => exception
            #slackappknoxfailed(exception)
        end
    end



#     Upload Application to Firebase Test Lab
    lane :uploadtofirebasetestlab do
        begin
            sh("/opt/homebrew/bin/gcloud firebase test android run --type robo --app /Users/rmltech/Documents/Appknox/Fastlane-App/app-release-protected.apk")
            #slacktfirebasetestlabsuccess
        rescue => exception
            #slackfirebasetestlabfailed(exception)
        end

    end

#     Run DexGuard Standalone
    lane :dexguardstandalone do
        sh("java -Ddexguard.license=/Users/rmltech/Documents/GuardSquare/DexGuard/Lisensi/baru/dexguard-license.txt -DANDROID_HOME=/Users/rmltech/Library/Android/sdk/platforms/android-34/android.jar -jar /Users/rmltech/Documents/GuardSquare/DexGuard/Versi/DexGuard-9.4.21/lib/dexguard.jar @/Users/rmltech/Documents/GuardSquare/DexGuard/dexguard-standalone.txt")
    end

#     Run DexGuard Standalone and Upload to Appknox
    lane :dexguardstandaloneuploadtoappknpx do
        begin
            dexguardstandalone()
            slackdexguardsuccess
        rescue => exception
            slackdexguarderror(exception)
        end

         begin
            sh("export APPKNOX_ACCESS_TOKEN=156e23bde8e3506cc5fd1bc8ae49b9d2a2d689ab")
            sh("/usr/local/bin/appknox upload /Users/rmltech/Documents/GuardSquare/Demo/Fastlane-DG-Standalone/app-release-protected.apk | xargs /usr/local/bin/appknox cicheck --risk-threshold critical")
            slackappknoxsuccess()
         rescue => exception
            slackappknoxfailed(exception)
         end
    end

 end