# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  # desc "Build Release Application With DexGuard"
  # lane  :releaseapps do
  #   gradle(
  #     task: 'assemble',
  #     build_type: 'Release'
  #   )
  #   # release = firebase_app_distribution(
  #   latest_release = firebase_app_distribution_get_latest_release(
  #     app: "1:954269003292:android:b4099e7352481e8e6239d9",
  #     firebase_cli_token: "1//0gt-XjFucD2qDCgYIARAAGBASNwF-L9IrXg1q10HqDfGeWS5J2f7NzFyYWHwvmBuy46cS1xFiClbPJ_pDzCYoKjxiXEZs6kytMDI"
  #     # testers: "nikkirufiansya2@gmail.com, nikkirufiansya88@gmail.com,rizkyprad.putra@gmail.com,technicalrml2023@gmail.com"
  #   )
  #   increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  # end

  lane :increment_version do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:954269003292:android:b4099e7352481e8e6239d9",
      firebase_cli_token: "1//0gt-XjFucD2qDCgYIARAAGBASNwF-L9IrXg1q10HqDfGeWS5J2f7NzFyYWHwvmBuy46cS1xFiClbPJ_pDzCYoKjxiXEZs6kytMDI"
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })

    release = firebase_app_distribution(
      app: "1:954269003292:android:b4099e7352481e8e6239d9",
      firebase_cli_token: "1//0gt-XjFucD2qDCgYIARAAGBASNwF-L9IrXg1q10HqDfGeWS5J2f7NzFyYWHwvmBuy46cS1xFiClbPJ_pDzCYoKjxiXEZs6kytMDI",
      testers: "nikkirufiansya2@rml.co.id, technicalrml2023@gmail.com"
    )

    gradle(
    task: 'clean'
    )
  end
end

